# Generated by Django 4.2.7 on 2025-03-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka_app', '0002_journal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
