# Generated by Django 4.2.7 on 2025-03-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eureka_app_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='journal',
            table='eureka_app_journal',
        ),
    ]
