# Generated by Django 4.2.7 on 2025-03-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka_app_entry', '0002_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='favorite',
            field=models.BooleanField(default=False, help_text='Indica si la entrada está marcada como favorita'),
        ),
    ]
